### PR TITLE
add new stencil paper, this one is without badges though

### PR DESCRIPTION
**Pull request by bastianhagedorn**

### CODE REVIEW

**Review by naummo — CHANGES_REQUESTED** [review]
Worth updating README as well.

**Comment by bastianhagedorn** [comment]
thanks for the notice, the README is now updated accordingly

**Review by naummo — APPROVED** [review]

**Review by michel-steuwer — CHANGES_REQUESTED** [review]
In the paper repository is a separate file called authorversion.tex 

You should use this to create the PDF we upload here, as this has the authorversion flag set in the LaTeX class options, which produces a slightly different licensing text and is extra provided by ACM for publishing papers on authors web pages.

@bastianhagedorn, could you please update the pull request with the new PDF (this new version will also have the badges on it).

**Comment by bastianhagedorn** [comment]
updated the pdf using the authorversion

**Review by michel-steuwer — APPROVED** [review]

**Pull request merged**
